class AppConsts {
  static const String icon = 'assets/icons/icon.png';
  static const String iconRound = 'assets/icons/icon_round.png';
  static const String iconSquare = 'assets/icons/icon_sq.png';
  static const String google = 'assets/google.png';
  static const String create = 'assets/bottom_bar/create.png';
  static const String selectedCreate = 'assets/bottom_bar/selected_create.png';
  static const String gallery = 'assets/bottom_bar/gallery.png';
  static const String selectedGallery =
      'assets/bottom_bar/selected_gallery.png';
  static const String settings = 'assets/bottom_bar/settings.png';
  static const String selectedSettings =
      'assets/bottom_bar/selected_settings.png';
  static const String textIcon = 'assets/artbotic.png';
  static const String instagram = 'assets/instagram.png';
  static const String discord = 'assets/discord.png';
  static const String diamond = 'assets/diamond.png';
  static const String inPainting = 'assets/inpainting.png';
  static const String text = 'assets/text.png';
  static const String edit = 'assets/edit.png';
  static const String idea = 'assets/idea.png';
  static const String colors = 'assets/colors.png';
  static const String addImage = 'assets/add_image.png';
  static const String upload = 'assets/upload.png';
  static const String crop = 'assets/crop.png';
  static const String arrowDown = 'assets/arrow_down.png';
  static const String brush = 'assets/brush.png';
  static const String oneToOne = 'assets/aspect_ratio/one_one.png';
  static const String nineToSix = 'assets/aspect_ratio/nine_six.png';
  static const String fourToThree = 'assets/aspect_ratio/four_three.png';
  static const String fourToFive = 'assets/aspect_ratio/four_five.png';
  static const String fiveToThree = 'assets/aspect_ratio/five_three.png';
  static const String sliderHead = 'assets/slider_head.png';
  static const String variation = 'assets/creation_detail/variation.png';
  static const String bin = 'assets/creation_detail/bin.png';
  static const String download = 'assets/creation_detail/download.png';
  static const String evolve = 'assets/creation_detail/evolve.png';
  static const String retouch = 'assets/creation_detail/retouch.png';
  static const String upscale = 'assets/creation_detail/upscale.png';
  static const String customerSupport = 'assets/settings/customer_support.png';
  static const String language = 'assets/settings/language.png';
  static const String moreApps = 'assets/settings/more_apps.png';
  static const String privacyPolicy = 'assets/settings/privacy_policy.png';
  static const String rateUs = 'assets/settings/rate_us.png';
  static const String share = 'assets/settings/share.png';
  static const String theme = 'assets/settings/theme.png';
  static const String king = 'assets/settings/king.png';
  static const String arrowRight = 'assets/settings/arrow_right.png';
}
